title: Linked Data, RDF Tools, Emacs, Architecture and beyond
description: Explore linked data, ontologies, RDF tools in Emacs, data conversion techniques, and ArchiMate modeling. Discusses Fuseki, data conversion and tools for for RDF analysis. Last but not least AI and RDF.
keywords: "Linked Data, RDF, Emacs, Ontologies, RDF Servers, Fuseki, Ontop, RDF-FDW, PostgreSQL, ArchiMate, Data Conversion"
theme: just-the-docs

collections:
  documents:
    permalink: "/:collection/:path/"
    output: true
  other:
    permalink: "/:collection/:path/"
    output: true
    
just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    documents:
      name: Semantics
    other:
      name: Architecture
      nav_fold: true
      
social_links:
     name: rss
     link: "/feed.xml"
  
url: https://just-the-docs.github.io
 
logo: "/assets/Logo-on-sematics.png"

callouts_level: loud # quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-feed
  - jekyll-sitemap
  

  
